name: Deploy Angular to AWS On Master Push

on:
  push:
    branches:
      - master
  workflow_dispatch: # allows manual trigger, no tag needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build -- --configuration production

      # Upload everything except JSON files
      - name: Upload non-JSON files to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --exclude "*.json"
        env:
          AWS_S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: dist/wedding-sc-fe/browser

      # Upload JSON translations with correct headers
      - name: Upload JSON translations with correct cache-control
        run: |
          aws s3 cp dist/wedding-sc-fe/browser/i18n/ s3://${{ vars.S3_BUCKET_NAME }}/i18n/ \
            --recursive \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "application/json"
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Invalidate CloudFront cache for entire site
      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
