name: Deploy Angular to AWS on Tag

on:
  push:
    tags:
      - '*'   # Auto-triggered on any tag
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to deploy (e.g., v1.0.0)'
        required: false

env:
  SOURCE_DIR: dist/wedding-sc-fe

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required if checking out a specific tag

      - name: Set TAG ref (manual or auto)
        id: tag_ref
        run: |
          TAG_NAME="${{ github.event.inputs.tag || github.ref_name }}"
          echo "Using tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Checkout tag
        if: github.event_name == 'workflow_dispatch'
        run: |
          git fetch --tags
          git checkout ${{ steps.tag_ref.outputs.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (production)
        run: npm run build -- --configuration production

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ vars.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          SOURCE_DIR: ${{ env.SOURCE_DIR }}

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          paths: '/*'
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
