name: Build Angular (Production) on Master Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm ci

      - name: Build Angular in production mode
        run: npm run build -- --configuration production
